import type { CaseStudy, ResearchEntry, WritingPost } from '../types';

export const site = {
  name: 'Sumudu Ratnayake',
  shortName: 'SR',
  headline: 'Curious builder exploring research, AI, and software.',
  subhead: 'Turning ideas into working systems that matter.',
  email: 'ishadi.leoni@gmail.com',
  location: 'Sri Lanka',
  github: 'https://github.com/Lilvamp237',
  linkedin: 'https://www.linkedin.com/in/sumudu-ratnayake-782b90235/',
  cv: 'cv/Sumudu Ratnayake - Resume.pdf',
  avatar: 'https://github.com/Lilvamp237.png',
};

export const navigation = [
  { label: 'Home', path: '/' },
  { label: 'About', path: '/about' },
  { label: 'Projects', path: '/projects' },
  { label: 'Research', path: '/research' },
  { label: 'Writing', path: '/writing' },
  { label: 'Currently', path: '/currently' },
  { label: 'Contact', path: '/contact' },
];

export const researchInterests = [
  'Agentic AI',
  'Multi-agent systems',
  'Explainable AI',
  'Human–computer interaction',
  'Accessibility',
  'Educational technology',
  'Virtual & extended reality',
  'Ontologies & semantic systems',
  'Knowledge graphs',
  'Responsible AI',
];

export const projects: CaseStudy[] = [
  {
    slug: 'ontology-vr-tutoring',
    title: 'Ontology-driven VR tutoring for Deaf and Hard of Hearing children',
    label: 'Research prototype · Accessibility · XR',
    summary: 'A featured research system connecting semantic knowledge and immersive tutoring for Deaf and Hard of Hearing learners.',
    technologies: ['VR/XR', 'Ontologies', 'Accessibility', 'Educational technology'],
    status: 'Needs details',
    featured: true,
    needs: ['Problem statement and research context', 'Personal role and collaborators', 'Implementation details and technology', 'Outcomes, links, and approved imagery'],
  },
  {
    slug: 'snomed-fhir-terminology',
    title: 'SNOMED CT & FHIR terminology server work',
    label: 'Professional work · Semantic systems',
    summary: 'Terminology and interoperability work involving SNOMED CT and FHIR. Public-safe project details are still needed before this case study can be expanded.',
    technologies: ['SNOMED CT', 'FHIR', 'Terminology services', 'Semantic systems'],
    status: 'Needs details',
    featured: true,
    needs: ['Public-safe context', 'Personal role and scope', 'Implementation and outcomes', 'Links or imagery that may be shared'],
  },
  {
    slug: 'athena',
    title: 'Athena',
    label: 'Competition project · AI · Cognitive wellness',
    summary: 'An AI-powered platform supporting cognitive wellness and dementia care management for patients and caregivers.',
    problem: 'Care teams need a clearer way to track daily activity, medication, wellness signals, and collaboration around people living with dementia.',
    context: 'Built as a competition project and recognised for its use of technology at Data Odyssey 2025.',
    implementation: 'The existing portfolio describes a React interface with analytics, sentiment tracking, medication management, team collaboration, and Python/Node.js AI features.',
    technologies: ['React', 'Python', 'Node.js', 'Chart.js', 'Jest'],
    outcome: 'Best Use of Technology — Data Odyssey 2025.',
    status: 'Completed',
    featured: true,
    needs: ['Repository URL', 'Personal role and team', 'Process and lessons learned', 'Approved screenshot'],
  },
  {
    slug: 'caresync',
    title: 'CareSync',
    label: 'Competition project · Full-stack software',
    summary: 'A team coordination and burnout-management platform with scheduling, wellness tracking, and secure collaboration for medical professionals.',
    problem: 'Demanding shifts, fragmented team communication, and limited visibility into personal wellness can compound burnout for medical professionals.',
    context: 'Developed for Code with WIE 2025.',
    implementation: 'A responsive Next.js application with a unified calendar, shift swaps, priority announcements, habit logs, Supabase, PostgreSQL, and row-level security.',
    technologies: ['Next.js', 'TypeScript', 'Supabase', 'PostgreSQL', 'Recharts'],
    outcome: '1st Runner-Up — Code with WIE 2025.',
    image: 'projects/caresync.png',
    repository: 'https://github.com/Lilvamp237/cww',
    status: 'Completed',
    featured: true,
    needs: ['Personal role', 'Design/research process', 'Lessons learned'],
  },
  {
    slug: 'bookstore-ontology-agents',
    title: 'Intelligent bookstore with ontology & multi-agent simulation',
    label: 'AI systems · Knowledge representation',
    summary: 'An autonomous bookstore simulation combining OWL, SWRL reasoning, agent-based modelling, and a graph database.',
    problem: 'Explore how domain knowledge and autonomous agents can coordinate inventory and customer activity in a transparent simulated environment.',
    implementation: 'OWL models domain knowledge; SWRL and Pellet infer conditions such as low stock; Mesa agents act on those inferences; Neo4j records relationships and transactions; Streamlit exposes live controls and visualisation.',
    technologies: ['Python', 'OWL / SWRL', 'Mesa', 'Neo4j', 'Streamlit'],
    image: 'projects/bookstore-ontology.png',
    repository: 'https://github.com/Lilvamp237/Bookstore-Management-System-with-Ontology-and-Multi-Agent-Simulation',
    status: 'Completed',
    featured: true,
    needs: ['Project outcome', 'Personal role', 'Lessons learned'],
  },
  {
    slug: 'hotel-agentic-optimizer',
    title: 'Agentic guest experience optimiser',
    label: 'Hackathon · Agentic AI',
    summary: 'A multi-stage system combining customer segmentation, prediction, RAG, weather, and local context for personalised hotel communications.',
    context: 'Developed for the Mini Hackathon semi-finals organised by the Statistics Circle, University of Colombo.',
    implementation: 'K-Means discovers behavioural segments, a Random Forest predicts segments, and an agentic RAG workflow produces context-aware messages in a Streamlit dashboard.',
    technologies: ['Python', 'scikit-learn', 'RAG', 'Streamlit', 'Pandas'],
    image: 'projects/hotel-experience.png',
    repository: 'https://github.com/Lilvamp237/Agentic-Based-Hotel-Booking-Guest-Experience-Optimizer',
    status: 'Completed',
    needs: ['Outcome', 'Personal role', 'Lessons learned'],
  },
  {
    slug: 'green-ai',
    title: 'Green AI',
    label: 'Sustainability · Data visualisation',
    summary: 'A web platform visualising AI model emissions and cloud data-centre energy use to support lower-carbon decisions.',
    implementation: 'A Vue 3 interface presents maps and dashboards, while Django processes datasets and supports carbon-footprint estimates and recommendations.',
    technologies: ['Vue 3', 'Django', 'Python', 'Pandas', 'REST APIs'],
    outcome: 'Champion — Data Odyssey 2024, as recorded in the existing portfolio.',
    image: 'projects/green-ai.jpg',
    repository: 'https://github.com/Lilvamp237/green-ai-new',
    status: 'Completed',
    needs: ['Personal role', 'Process', 'Lessons learned'],
  },
  {
    slug: 'egov-platform',
    title: 'eGOV',
    label: 'Competition project · Civic systems',
    summary: 'A multi-portal e-government platform for citizen services, administration, and analytics.',
    implementation: 'A Next.js monorepo coordinates citizen, admin, and analytics applications with shared packages, Supabase/PostgreSQL, role-based access, and Docker development workflows.',
    technologies: ['Next.js', 'TypeScript', 'Supabase', 'PostgreSQL', 'Docker'],
    image: 'projects/egov-monorepo.jpg',
    repository: 'https://github.com/HasinduNimesh/Mental-Breakdown_eGOV',
    status: 'Completed',
    needs: ['Personal role', 'Competition context and outcome', 'Lessons learned'],
  },
  {
    slug: 'smart-home-energy',
    title: 'Smart home energy tracker',
    label: 'Full-stack · ML · Semantic web',
    summary: 'A system that tracks household energy, predicts near-term consumption, and uses semantic rules to suggest lower-cost usage patterns.',
    implementation: 'React and Flask provide the product layer; engineered time-series features feed a regression model; an RDF ontology and SPARQL rules reason over time-of-use pricing.',
    technologies: ['React', 'Flask', 'scikit-learn', 'RDF / SPARQL', 'SQLite'],
    repository: 'https://github.com/Lilvamp237/Smart-Home-Energy-Tracker',
    status: 'Completed',
    needs: ['Project image', 'Outcome', 'Personal role', 'Lessons learned'],
  },
  {
    slug: 'audio-denoising',
    title: 'Sup_Audio',
    label: 'Deep learning · Desktop software',
    summary: 'An end-to-end audio denoising application using a U-Net model and a desktop interface for recording, playback, and cleaned output.',
    implementation: 'The pipeline transforms audio with STFT, performs spectrogram inference in fixed-length chunks, reconstructs output, and exposes the workflow through PyQt5.',
    technologies: ['Python', 'TensorFlow', 'Keras', 'PyQt5', 'librosa'],
    image: 'projects/audio-denoising.png',
    repository: 'https://github.com/Lilvamp237/Audio-Denoising-System-using-Deep-Learning-and-PyQt-UI-',
    status: 'Completed',
    needs: ['Outcome', 'Personal role', 'Lessons learned'],
  },
  {
    slug: 'face-recognition-attendance',
    title: 'Face recognition attendance system',
    label: 'Computer vision · Desktop software',
    summary: 'A real-time attendance system with registration, identity verification, local records, and weekly statistics.',
    implementation: 'OpenCV and DeepFace provide face processing and embedding-based matching; PyQt5 supports registration, attendance, and reporting workflows.',
    technologies: ['Python', 'OpenCV', 'DeepFace', 'PyQt5'],
    image: 'projects/face-recognition.png',
    repository: 'https://github.com/Lilvamp237/face_recognition_attendance_system',
    status: 'Completed',
    needs: ['Outcome', 'Personal role', 'Lessons learned'],
  },
  {
    slug: 'budget-buddy',
    title: 'Budget Buddy',
    label: 'University project · Java',
    summary: 'A desktop personal-finance manager for income, expenses, balances, and budget summaries.',
    context: 'Built as a second-year object-oriented programming group assignment.',
    implementation: 'A Java Swing interface organised with an MVC-inspired structure, reusable GUI components, event-driven behaviour, and local file handling.',
    technologies: ['Java', 'Swing', 'File I/O', 'MVC'],
    image: 'projects/budget-buddy.jpg',
    repository: 'https://github.com/Lilvamp237/Budget-Buddy---Financial-Tracker',
    status: 'Completed',
    needs: ['Personal role', 'Outcome', 'Lessons learned'],
  },
];

export const publications: ResearchEntry[] = [
  {
    slug: 'inclusive-digital-infrastructure',
    title: 'AI-Driven Inclusive Digital Infrastructure: A Unified Cognitive Load Framework for Accessible Smart Education in Sustainable Cities',
    venue: 'International Conference on Sustainable Developments in Computer Engineering, Green Technology & Smart Systems — Hooghly Engineering & Technology College',
    year: '2025',
    status: 'Published',
    summary: 'An accessibility framework for smart education that adapts multimodal content for Deaf and Hard of Hearing and Blind and Visually Impaired users using cognitive-load estimation.',
    needs: ['Authors', 'Paper/proceedings link', 'Presentation', 'Citation'],
  },
  {
    slug: 'sleepzy',
    title: 'Designing Sleepzy: A Mobile Interface for Lucid Dream Induction via Smart Pillow Technology',
    venue: '18th International Research Conference — General Sir John Kotelawala Defence University',
    year: '2025',
    status: 'Published',
    summary: 'A user-centred mobile interface and adaptive intervention framework for REM detection, personalised sensory cues, and sleep support.',
    proceeding: 'https://irc.kdu.ac.lk/2025/documents/2025/abstracts/irc25_abstract_book_foc.pdf',
    needs: ['Authors', 'Paper link', 'Presentation', 'Citation'],
  },
  {
    slug: 'green-cloud-framework',
    title: 'A Unified Framework for SLA-Aware and Carbon-Conscious Green Cloud Computing: A Holistic Approach to Sustainable',
    venue: '18th International Research Conference — General Sir John Kotelawala Defence University',
    year: '2025',
    status: 'Needs review',
    summary: 'A multi-objective framework balancing energy, carbon emissions, and service-level agreements in green cloud computing.',
    proceeding: 'https://irc.kdu.ac.lk/2025/documents/2025/abstracts/irc25_abstract_book_foc.pdf',
    needs: ['Confirm complete title', 'Authors', 'Paper link', 'Presentation', 'Citation'],
  },
  {
    slug: 'sustainability-awareness-apps',
    title: 'Enhancing Sustainability Awareness Through Mobile Applications: A Comparative Case Study and Analysis',
    venue: '18th International Research Conference — General Sir John Kotelawala Defence University',
    year: '2025',
    status: 'Published',
    summary: 'A comparative analysis of sustainability applications identifying technical and interface gaps that affect retention and real-world impact.',
    proceeding: 'https://irc.kdu.ac.lk/2025/documents/2025/abstracts/irc25_abstract_book_fmsh.pdf',
    needs: ['Authors', 'Paper link', 'Presentation', 'Citation'],
  },
];

export const writing: WritingPost[] = [
  {
    slug: 'the-joy-of-seeing-something-work',
    title: 'The Joy of Seeing Something I Built Actually Work',
    excerpt: 'A reflection on the small, unmistakable moment when an idea stops being abstract and starts behaving like a real thing.',
    category: 'Reflections', tags: ['building', 'learning'], featured: true, status: 'Planned',
    outline: ['The first satisfying feedback loop', 'Why working prototypes change how I think', 'Keeping that feeling as systems get larger'],
  },
  {
    slug: 'learning-programming-before-ai',
    title: 'Learning Programming Before AI',
    excerpt: 'Books, documentation, Stack Overflow, experiments, and the habits that came from learning before assistants became part of the workflow.',
    category: 'Journey', tags: ['learning', 'AI', 'fundamentals'], featured: true, status: 'Planned',
    outline: ['Learning from slow feedback', 'Why I avoided AI for OOP and DSA', 'How I use AI now without outsourcing understanding'],
  },
  {
    slug: 'the-unexpected-reason-i-started-research',
    title: 'The Unexpected Reason I Started Research',
    excerpt: 'What began as a practical goal to present at a conference became a genuine interest in difficult questions, publishing, and explaining ideas.',
    category: 'Research Rabbit Holes', tags: ['research', 'journey'], status: 'Planned',
    outline: ['A conference as the initial goal', 'Learning what research actually asks of you', 'Why I stayed interested'],
  },
  {
    slug: 'building-is-my-favourite-way-to-learn',
    title: 'Building Things Is My Favourite Way to Learn',
    excerpt: 'Why prototypes, mistakes, and working systems are the most useful map I have found for learning unfamiliar ideas.',
    category: 'Build Logs', tags: ['building', 'learning'], status: 'Planned',
    outline: ['Turning ambiguity into questions', 'What implementation reveals', 'A practical loop for learning by building'],
  },
];

export const currently = {
  updated: 'Add date',
  items: [
    { label: 'Building', text: 'Add current product, prototype, or startup work.' },
    { label: 'Researching', text: 'Ontology-driven VR tutoring, agentic AI, XAI, and semantic systems.' },
    { label: 'Writing', text: 'Preparing the first essays for this site.' },
    { label: 'Learning', text: 'Add the topic, tool, or question currently being explored.' },
    { label: 'Reading', text: 'Add the current book, paper, or reading list.' },
    { label: 'Working on', text: 'Add a public-safe summary of current professional or startup work.' },
  ],
};

export const education = [
  { period: '2023 — Present', title: 'BSc (Hons) in Computer Science', place: 'Undergraduate', detail: 'Current portfolio records a focus across AI/ML, data science, and software development.' },
  { period: '2019 — 2021', title: 'GCE Advanced Level', place: 'Physical Science stream', detail: 'Combined Mathematics, Physics, and Information & Communication Technology.' },
];

export const achievements = [
  { year: '2025', title: 'ICDS Mini-Hackathon', result: 'Top 15 finalist' },
  { year: '2025', title: 'Code with WIE', result: '1st Runner-Up' },
  { year: '2025', title: 'Data Odyssey', result: 'Best Use of Technology' },
  { year: '2025', title: 'InnovateX University Edition', result: '1st Runner-Up' },
  { year: '2025', title: 'CodeRally 6.0', result: 'Advanced Tier finalist' },
  { year: '2025', title: 'Tech-Triathlon', result: 'Top 8 finalist from 170+ teams' },
  { year: '2024', title: "Vice Chancellor's List", result: 'YGPA 3.82 / 4.0' },
  { year: '2024', title: 'Data Odyssey', result: 'Champion — Green AI' },
  { year: '2023', title: "Dean's List", result: 'YGPA 3.78 / 4.0' },
];
