import type { CaseStudy, ResearchEntry, WritingPost } from '../types';

export const site = {
  name: 'Sumudu Ratnayake',
  shortName: 'SR',
  headline: 'Curious builder exploring AI, Research, and Software.',
  subhead: 'Turning ideas into working systems that matter.',
  email: 'ishadi.leoni@gmail.com',
  location: 'Sri Lanka',
  github: 'https://github.com/Lilvamp237',
  linkedin: 'https://www.linkedin.com/in/sumudu-ratnayake-782b90235/',
  cv: 'cv/Sumudu Ishadi Ratnayake.pdf',
  avatar: 'sumudu-profilepic.jpeg',
};

export const navigation = [
  { label: 'Home', path: '/' },
  { label: 'About', path: '/about' },
  { label: 'Toolkit', path: '/toolkit' },
  { label: 'Projects', path: '/projects' },
  { label: 'Research', path: '/research' },
  { label: 'Blog', path: '/writing' },
  { label: 'Contact', path: '/contact' },
];

export const techStack: Record<string, string[]> = {
  'Languages': ['Python', 'Java', 'C++', 'Dart', 'TypeScript', 'SQL', 'C#'],
  'AI frameworks': ['TensorFlow', 'Keras', 'Scikit-Learn', 'DeepFace', 'RASA', 'LangChain', 'LangGraph'],
  'Web & mobile': ['React.js', 'Next.js', 'Vue.js', 'Tailwind CSS', 'Flutter'],
  'Data & databases': ['Pandas', 'Matplotlib', 'Neo4j', 'PostgreSQL', 'MySQL', 'Firebase', 'Supabase'],
  'Cloud & DevOps': ['Git', 'Docker', 'Azure ML', 'Postman', 'Oracle Cloud'],
  'XR & hardware': ['Arduino', 'Unity', 'VR Foundation', 'IoT Sensors'],
};

export const certifications = [
  { name: 'Machine Learning with Python Professional Certificate', provider: 'Anaconda Inc', date: 'Dec 2025', verify: 'https://www.linkedin.com/learning/certificates/c285391c2d76739b9216d3120122d9d6a1a37e61f77870596c28fb045b3d1741' },
  { name: 'GitHub Copilot', provider: 'Microsoft', date: 'Dec 2025', verify: 'https://learn.microsoft.com/api/credentials/share/en-us/Sumudu05-1888/7E05411E38180AC0?sharingId' },
  { name: 'Neo4j Certified Professional', provider: 'Neo4j', date: 'Dec 2025', verify: 'https://graphacademy.neo4j.com/c/1cf2e865-fa34-4ab9-be28-d889e67dbbb9/' },
  { name: 'Oracle Cloud Infrastructure 2025 Certified AI Foundations Associate', provider: 'Oracle', date: 'Sep 2025', verify: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=BCA92DFDF1EE5C98047C5CD7EF1090710F40E633B651CD271D84425D0981BF90' },
  { name: 'Intro to Machine Learning', provider: 'Kaggle', date: 'Aug 2025', verify: 'https://www.kaggle.com/learn/certification/sumuu237/intro-to-machine-learning' },
  { name: 'Unity Essentials Pathway', provider: 'Unity', date: 'Jul 2025', verify: 'https://www.credly.com/badges/20d7c767-4e53-460c-8d4c-192b02759373/linked_in_profile' },
  { name: 'Postman API Fundamentals Student Expert', provider: 'Postman', date: 'Feb 2025', verify: 'https://api.badgr.io/public/assertions/yKS5WPrYQJC1nIIOwBfPUw' },
  { name: 'Microsoft Certified: Azure AI Fundamentals', provider: 'Microsoft', date: 'Feb 2023', verify: 'https://www.credly.com/badges/e41626c1-8082-491c-a89e-391a0294e5dc/public_url' },
  { name: 'CCNA: Introduction to Networks', provider: 'Cisco', date: 'Nov 2023' },
];

export const researchInterests = [
  'Agentic AI',
  'Multi-agent systems',
  'Explainable AI',
  'Human–computer interaction',
  'Accessibility',
  'Educational technology',
  'Virtual & extended reality',
  'Ontologies & semantic systems',
  'Knowledge graphs',
  'Responsible AI',
];

export const projects: CaseStudy[] = [
  {
    slug: 'dengue-allocator',
    title: 'DengueSentinel, dengue vector-control resource allocator',
    label: 'Decision support · Public health',
    summary: 'A forecasting and optimisation platform that predicts dengue transmission risk 2–4 weeks ahead and allocates vector-control teams within budget constraints.',
    implementation: 'A three-stage pipeline forecasts district-level risk with SARIMA/LightGBM/seasonal-naive ensembles, estimates intervention impact with SEI-SIR compartmental modelling, and allocates teams via integer linear programming (PuLP/CBC). Role-based Streamlit dashboards serve the public, hospital staff, regional officers, and administrators, with strict data-provenance tracking and an offline-first design.',
    technologies: ['Python', 'LightGBM', 'statsmodels', 'PuLP / CBC', 'Streamlit'],
    categories: ['Competition', 'AI/ML'],
    image: 'projects/dengue-allocator.png',
    team: ['Dinuka', 'Hasindu'],
    repository: 'https://github.com/Wicky2002/dengue-allocator',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'nourish-loop',
    title: 'NourishLoop',
    label: 'Decision support · EdTech',
    summary: 'A closed-loop, human-in-the-loop platform for nutritious, affordable, low-waste school meal planning in Sri Lanka.',
    implementation: 'A Next.js/FastAPI system forecasts meal demand with an exponential-moving-average model, optimises meal recommendations against nutrition and budget constraints, and retrains its demand model from real consumption data (attendance, leftovers), with dual dashboards for meal planners and coordinators.',
    technologies: ['Next.js', 'TypeScript', 'FastAPI', 'shadcn/ui', 'Recharts'],
    categories: ['Competition', 'Passion project', 'Full-stack', 'AI/ML'],
    image: 'projects/nourish-loop.png',
    team: ['Dinuka'],
    repository: 'https://github.com/Lilvamp237/nourish-loop',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'pokemon-meta-balance',
    title: 'Pokémon predictive meta-balance system',
    label: 'Applied ML · Game design tooling',
    summary: 'A machine learning system analysing Pokémon stats and typing to help assess game-balance risk and predict competitive viability across generations.',
    implementation: 'An unsupervised Isolation Forest flags mathematically anomalous stat designs for balance review, while a Random Forest regressor predicts how many future generations a design stays competitively viable, surfaced through an explainable Streamlit dashboard with separate views for designers and competitive players.',
    technologies: ['Python', 'scikit-learn', 'Streamlit', 'Pandas'],
    categories: ['Passion project', 'AI/ML'],
    image: 'projects/pokemon-meta-balance.png',
    team: ['Dinuka', 'Sasini', 'Gimhani', 'Malick', 'Senuda'],
    repository: 'https://github.com/Lilvamp237/Predictive-Meta-Balance-System-for-Pokemon',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'ithihaasa-guru',
    title: 'Ithihaasa Guru',
    label: 'AI · EdTech · Ontologies',
    summary: 'An AI platform that automates scoring and feedback for open-ended Sri Lankan colonial-history questions, delivered in Sinhala medium.',
    implementation: 'A LangGraph workflow combines an OWL ontology (RDFLib) with RAG retrieval over Grade 8–11 textbooks (FAISS) and a locally-run LLM (Ollama, gemma3:12b) to generate evidence-based scoring and detailed Sinhala feedback with confidence scoring, through a Streamlit interface.',
    technologies: ['LangGraph', 'FAISS', 'OWL / RDFLib', 'Ollama', 'Streamlit'],
    categories: ['Assignment', 'AI/ML', 'Agent systems'],
    image: 'projects/ithihaasa-guru.png',
    repository: 'https://github.com/Lilvamp237/Ithihaasa-Guru',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'autonomous-swarms',
    title: 'Autonomous vehicle swarms, social value orientation study',
    label: 'Simulation · Agentic systems',
    summary: 'A simulation of autonomous vehicle swarms at urban intersections, studying how individual social preferences shape collective traffic outcomes.',
    implementation: 'Agents built on Eclipse SUMO and the TraCI client use Social Value Orientation utility functions and Nash-style conflict resolution to decide yield/proceed behaviour at intersections. An inverse-reinforcement-learning module estimates each agent’s SVO angle from observed driving, while Neo4j records interaction history alongside CSV telemetry (delay, throughput, collisions).',
    technologies: ['Python', 'Eclipse SUMO', 'TraCI', 'Neo4j'],
    categories: ['Research prototype', 'Agent systems'],
    image: 'projects/autonomous-swarms.png',
    team: ['Dinuka', 'Sasini', 'Senuda'],
    repository: 'https://github.com/Lilvamp237/Autonomous-swarms',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'athena',
    title: 'Athena',
    label: 'Competition project · AI · Cognitive wellness',
    summary: 'An AI-powered platform supporting cognitive wellness and dementia care management for patients and caregivers.',
    problem: 'Care teams need a clearer way to track daily activity, medication, wellness signals, and collaboration around people living with dementia.',
    context: 'Built as a competition project and recognised for its use of technology at Data Odyssey 2025.',
    implementation: 'The existing portfolio describes a React interface with analytics, sentiment tracking, medication management, team collaboration, and Python/Node.js AI features.',
    technologies: ['React', 'Python', 'Node.js', 'Chart.js', 'Jest'],
    categories: ['Passion project', 'Competition', 'AI/ML', 'Data', 'Full-stack'],
    outcome: 'Best Use of Technology, Data Odyssey 2025.',
    image: 'projects/athena-1.png',
    team: ['Dinuka'],
    status: 'Completed',
    featured: true,
    needs: ['Repository URL'],
  },
  {
    slug: 'caresync',
    title: 'CareSync',
    label: 'Competition project · Full-stack software',
    summary: 'A team coordination and burnout-management platform with scheduling, wellness tracking, and secure collaboration for medical professionals.',
    problem: 'Demanding shifts, fragmented team communication, and limited visibility into personal wellness can compound burnout for medical professionals.',
    context: 'Developed for Code with WIE 2025.',
    implementation: 'A responsive Next.js application with a unified calendar, shift swaps, priority announcements, habit logs, Supabase, PostgreSQL, and row-level security.',
    technologies: ['Next.js', 'TypeScript', 'Supabase', 'PostgreSQL', 'Recharts'],
    categories: ['Passion project', 'Competition', 'Full-stack'],
    outcome: '1st Runner-Up, Code with WIE 2025.',
    image: 'projects/caresync.png',
    team: ['Dinuka'],
    repository: 'https://github.com/Lilvamp237/cww',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'bookstore-ontology-agents',
    title: 'Intelligent bookstore with ontology & multi-agent simulation',
    label: 'AI systems · Knowledge representation',
    summary: 'An autonomous bookstore simulation combining OWL, SWRL reasoning, agent-based modelling, and a graph database.',
    problem: 'Explore how domain knowledge and autonomous agents can coordinate inventory and customer activity in a transparent simulated environment.',
    implementation: 'OWL models domain knowledge; SWRL and Pellet infer conditions such as low stock; Mesa agents act on those inferences; Neo4j records relationships and transactions; Streamlit exposes live controls and visualisation.',
    technologies: ['Python', 'OWL / SWRL', 'Mesa', 'Neo4j', 'Streamlit'],
    categories: ['Passion project', 'Agent systems'],
    image: 'projects/bookstore-ontology.png',
    repository: 'https://github.com/Lilvamp237/Bookstore-Management-System-with-Ontology-and-Multi-Agent-Simulation',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'hotel-agentic-optimizer',
    title: 'Agentic guest experience optimiser',
    label: 'Hackathon · Agentic AI',
    summary: 'A multi-stage system combining customer segmentation, prediction, RAG, weather, and local context for personalised hotel communications.',
    context: 'Developed for the Mini Hackathon semi-finals organised by the Statistics Circle, University of Colombo.',
    implementation: 'K-Means discovers behavioural segments, a Random Forest predicts segments, and an agentic RAG workflow produces context-aware messages in a Streamlit dashboard.',
    technologies: ['Python', 'scikit-learn', 'RAG', 'Streamlit', 'Pandas'],
    categories: ['Competition', 'AI/ML', 'Data', 'Agent systems'],
    image: 'projects/hotel-experience.png',
    team: ['Dinuka', 'Savini'],
    repository: 'https://github.com/Lilvamp237/Agentic-Based-Hotel-Booking-Guest-Experience-Optimizer',
    status: 'Completed',
  },
  {
    slug: 'green-ai',
    title: 'Green AI',
    label: 'Sustainability · Data visualisation',
    summary: 'A web platform visualising AI model emissions and cloud data-centre energy use to support lower-carbon decisions.',
    implementation: 'A Vue 3 interface presents maps and dashboards, while Django processes datasets and supports carbon-footprint estimates and recommendations.',
    technologies: ['Vue 3', 'Django', 'Python', 'Pandas', 'REST APIs'],
    categories: ['Competition', 'AI/ML', 'Data'],
    outcome: 'Champion, Data Odyssey 2024, as recorded in the existing portfolio.',
    image: 'projects/green-ai.jpg',
    team: ['Sasini', 'Amna', 'Yuthara'],
    repository: 'https://github.com/Lilvamp237/green-ai-new',
    status: 'Completed',
  },
  {
    slug: 'egov-platform',
    title: 'eGOV',
    label: 'Competition project · Civic systems',
    summary: 'A multi-portal e-government platform for citizen services, administration, and analytics.',
    implementation: 'A Next.js monorepo coordinates citizen, admin, and analytics applications with shared packages, Supabase/PostgreSQL, role-based access, and Docker development workflows.',
    technologies: ['Next.js', 'TypeScript', 'Supabase', 'PostgreSQL', 'Docker'],
    categories: ['Competition', 'Full-stack'],
    image: 'projects/egov-monorepo.jpg',
    team: ['Team ClapTac'],
    repository: 'https://github.com/HasinduNimesh/Mental-Breakdown_eGOV',
    status: 'Completed',
  },
  {
    slug: 'smart-home-energy',
    title: 'Smart home energy tracker',
    label: 'Full-stack · ML · Semantic web',
    summary: 'A system that tracks household energy, predicts near-term consumption, and uses semantic rules to suggest lower-cost usage patterns.',
    implementation: 'React and Flask provide the product layer; engineered time-series features feed a regression model; an RDF ontology and SPARQL rules reason over time-of-use pricing.',
    technologies: ['React', 'Flask', 'scikit-learn', 'RDF / SPARQL', 'SQLite'],
    categories: ['Passion project', 'AI/ML', 'Full-stack', 'Agent systems'],
    team: ['Dinuka'],
    repository: 'https://github.com/Lilvamp237/Smart-Home-Energy-Tracker',
    status: 'Completed',
    needs: ['Project image'],
  },
  {
    slug: 'audio-denoising',
    title: 'Sup_Audio',
    label: 'Deep learning · Desktop software',
    summary: 'An end-to-end audio denoising application using a U-Net model and a desktop interface for recording, playback, and cleaned output.',
    implementation: 'The pipeline transforms audio with STFT, performs spectrogram inference in fixed-length chunks, reconstructs output, and exposes the workflow through PyQt5.',
    technologies: ['Python', 'TensorFlow', 'Keras', 'PyQt5', 'librosa'],
    categories: ['Passion project', 'AI/ML'],
    image: 'projects/audio-denoising.png',
    repository: 'https://github.com/Lilvamp237/Audio-Denoising-System-using-Deep-Learning-and-PyQt-UI-',
    status: 'Completed',
  },
  {
    slug: 'face-recognition-attendance',
    title: 'Face recognition attendance system',
    label: 'Computer vision · Desktop software',
    summary: 'A real-time attendance system with registration, identity verification, local records, and weekly statistics.',
    implementation: 'OpenCV and DeepFace provide face processing and embedding-based matching; PyQt5 supports registration, attendance, and reporting workflows.',
    technologies: ['Python', 'OpenCV', 'DeepFace', 'PyQt5'],
    categories: ['Assignment', 'AI/ML', 'Computer vision'],
    image: 'projects/face-recognition.png',
    repository: 'https://github.com/Lilvamp237/face_recognition_attendance_system',
    status: 'Completed',
  },
  {
    slug: 'budget-buddy',
    title: 'Budget Buddy',
    label: 'University project · Java',
    summary: 'A desktop personal-finance manager for income, expenses, balances, and budget summaries.',
    context: 'Built as a second-year object-oriented programming group assignment.',
    implementation: 'A Java Swing interface organised with an MVC-inspired structure, reusable GUI components, event-driven behaviour, and local file handling.',
    technologies: ['Java', 'Swing', 'File I/O', 'MVC'],
    categories: ['Assignment', 'Java'],
    image: 'projects/budget-buddy.jpg',
    team: ['Sasini', 'Senuda'],
    repository: 'https://github.com/Lilvamp237/Budget-Buddy---Financial-Tracker',
    status: 'Completed',
  },
  {
    slug: 'drug-category-prediction',
    title: 'Mental health-driven drug category prediction',
    label: 'Data science · Healthcare',
    summary: 'A machine learning system predicting drug categories from mental health conditions and usage patterns using XGBoost with PSO-based feature selection.',
    context: 'Built for the preliminary round of the ICDS 2025 Mini-Hackathon, organised by the University of Colombo with OCTAVE (JKH Group).',
    implementation: 'A preprocessing pipeline with scaling, imputation, and Particle Swarm Optimization for feature selection feeds an XGBoost classifier, with automated encoding/decoding and reproducible submission generation.',
    technologies: ['Python', 'XGBoost', 'scikit-learn', 'pandas', 'NumPy'],
    categories: ['Competition', 'AI/ML'],
    repository: 'https://github.com/Lilvamp237/Mental-health-condition-related-to-drug-usage---Drug-Prediction',
    initials: 'MH',
    team: ['Dinuka'],
    status: 'Completed',
  },
  {
    slug: 'smart-study-companion',
    title: 'Smart Study Companion',
    label: 'Full-stack · AI/NLP',
    summary: 'A full-stack web app helping students track study sessions, take notes, and use AI tools for summarisation, flashcards, quizzes, and study plans.',
    implementation: 'A Django REST Framework backend and React frontend integrate Hugging Face models (BART, DistilBERT) for summarisation, flashcard creation, question answering, sentiment analysis, keyword extraction, and quiz generation, with JWT auth and progress analytics.',
    technologies: ['Django', 'React', 'Hugging Face Transformers', 'PyTorch', 'JWT'],
    categories: ['Passion project', 'AI/ML', 'Full-stack'],
    repository: 'https://github.com/Wicky2002/smart-study-companion',
    initials: 'SSC',
    team: ['Dinuka'],
    status: 'Completed',
  },
  {
    slug: 'moot-society-website',
    title: 'Moot Society of Sri Lanka Law College, official website',
    label: 'Full-stack · CMS',
    summary: 'A responsive website for the Moot Society showcasing events, achievements, news, and a gallery, built on a Next.js and Strapi CMS stack.',
    implementation: 'A Next.js frontend with scroll animations and a lightbox gallery consumes a Strapi CMS backend with PostgreSQL/SQLite, Cloudinary media uploads, and role-based authentication. The site is SEO-optimised and production-ready.',
    technologies: ['Next.js', 'TypeScript', 'Strapi CMS', 'Tailwind CSS', 'Cloudinary'],
    categories: ['Passion project', 'Full-stack'],
    repository: 'https://github.com/Lilvamp237/moot-society-website',
    image: 'projects/moot-society.png',
    team: ['Dinuka'],
    status: 'Completed',
  },
  {
    slug: 'sumudus-todo-list',
    title: "Sumudu's ToDo List, smart Android task manager",
    label: 'Mobile · Android',
    summary: 'An Android task manager with offline support, Firebase sync, and exact alarm-based reminders that persist across reboots.',
    implementation: 'Built with Jetpack Compose and Kotlin on an MVVM architecture. Room handles local persistence for offline use, Firebase Authentication and Firestore provide sync, and AlarmManager with BroadcastReceivers drives exact, reboot-safe reminders. Material Design 3 supports adaptive light/dark theming.',
    technologies: ['Kotlin', 'Jetpack Compose', 'Room', 'Firebase', 'Hilt'],
    categories: ['Assignment', 'Mobile'],
    repository: 'https://github.com/Lilvamp237/SumudusToDoList',
    image: 'projects/todo-android.jpg',
    status: 'Completed',
  },
  {
    slug: 'localloop',
    title: 'Localloop, full-stack service integration platform',
    label: 'Hackathon · Full-stack',
    summary: 'A full-stack app demonstrating REST-based communication between a Ballerina backend and a Vite-powered frontend.',
    context: 'Developed for the Innovate with Ballerina 2025 competition.',
    implementation: 'A Ballerina backend exposes RESTful APIs for data processing and service logic; a Vite frontend consumes them for a fast, responsive UI, emphasising clean separation between layers and real-time data flow.',
    technologies: ['Ballerina', 'Vite', 'JavaScript', 'REST APIs'],
    categories: ['Competition', 'Full-stack'],
    initials: 'LL',
    team: ['Dinuka', 'Sasini', 'Senuda'],
    status: 'Completed',
    needs: ['Repository URL'],
  },
  {
    slug: 'e-shuttle',
    title: 'E-Shuttle',
    label: 'University project · Mobile',
    summary: 'A cross-platform Flutter app for campus shuttle/transport coordination, built with Firebase.',
    context: 'Built as a second-year university project.',
    technologies: ['Flutter', 'Dart', 'Firebase'],
    categories: ['Assignment', 'Mobile'],
    initials: 'ES',
    repository: 'https://github.com/Lilvamp237/e_shuttleee',
    status: 'Completed',
    needs: ['Project description and scope', 'Outcome'],
  },
];

export const publications: ResearchEntry[] = [
  {
    slug: 'bridging-semantic-gap-deaf-education',
    title: 'Bridging the Semantic Gap in Deaf Education: A Review of Virtual Reality Platforms and Knowledge-Based AI Approaches',
    authors: 'Sumudu Ratnayake',
    venue: '1st Jayewardenepura Computing Symposium (JCoS 2026)',
    year: '2026',
    date: 'May 20, 2026',
    status: 'Published',
    typeNote: 'Local conference · Abstract only · Published in proceedings',
    summary: 'A review of virtual reality platforms and knowledge-based AI approaches for bridging the semantic gap in Deaf education.',
    presentation: 'https://drive.google.com/file/d/1IwiRekxcJyuSWw7QzF-h5auNpb_I60o3/view?usp=sharing',
  },
  {
    slug: 'inclusive-digital-infrastructure',
    title: 'AI-Driven Inclusive Digital Infrastructure: A Unified Cognitive Load Framework for Accessible Smart Education in Sustainable Cities',
    authors: 'Dinuka Wickramasinghe, Sumudu Ratnayake, Dr. Kaneeka Vidanage, Mrs. Dharani Abeysinghe, Prof. Sabyasachi Bhattacharyya',
    venue: 'CRC Press, Taylor & Francis, Book chapter in "Sustainable Developments in Computer Engineering, Green Technology and Smart Systems" (ICSDS India-2025)',
    year: '2025',
    date: 'Dec 20, 2025',
    status: 'Published',
    typeNote: 'International conference · Full paper in proceedings · Book chapter (CRC Press, Taylor & Francis)',
    summary: 'An accessibility framework for smart education that adapts multimodal content for Deaf and Hard of Hearing and Blind and Visually Impaired users using cognitive-load estimation.',
    paper: 'https://www.taylorfrancis.com/chapters/edit/10.1201/9781003743774-148/ai-driven-inclusive-digital-infrastructure-unified-cognitive-load-framework-accessible-smart-education-sustainable-cities-dinuka-wickramasinghe-sumudu-ratnayake-kaneeka-vidanage-dharani-abeysinghe-sabyasachi-bhattacharyya',
    citation: 'DOI: 10.1201/9781003743774 · eBook ISBN: 9781003743774',
    presentation: 'https://drive.google.com/file/d/1UbZR1Q5i0rgdkW9fzEldleChZfwiarNv/view?usp=sharing',
  },
  {
    slug: 'sustainability-awareness-apps',
    title: 'Enhancing Sustainability Awareness Through Mobile Applications: A Comparative Case Study and Analysis',
    authors: 'Sumudu Ratnayake, Dinuka Wickramasinghe',
    venue: '18th International Research Conference, General Sir John Kotelawala Defence University (KDU IRC - 2025)',
    year: '2025',
    date: 'Oct 1, 2025',
    status: 'Published',
    typeNote: 'International conference · Abstract published in proceedings',
    summary: 'A comparative analysis of sustainability applications identifying technical and interface gaps that affect retention and real-world impact.',
    proceeding: 'https://irc.kdu.ac.lk/2025/documents/2025/abstracts/irc25_abstract_book_fmsh.pdf',
    presentation: 'https://drive.google.com/file/d/1DjHL0hEHq2zpbhAFdwzmcaDpXQ9Ld6xs/view?usp=sharing',
  },
  {
    slug: 'green-cloud-framework',
    title: 'A Unified Framework for SLA-Aware and Carbon-Conscious Green Cloud Computing: A Holistic Approach to Sustainable Infrastructure',
    authors: 'Sumudu Ratnayake, Dinuka Wickramasinghe',
    venue: '18th International Research Conference, General Sir John Kotelawala Defence University (KDU IRC - 2025)',
    year: '2025',
    date: 'Oct 1, 2025',
    status: 'Published',
    typeNote: 'International conference · Abstract published in proceedings',
    summary: 'A multi-objective framework balancing energy, carbon emissions, and service-level agreements in green cloud computing.',
    proceeding: 'https://irc.kdu.ac.lk/2025/documents/2025/abstracts/irc25_abstract_book_foc.pdf',
    presentation: 'https://drive.google.com/file/d/1Zho_1k1EmvoMyd-kCGkDFJYST1lJVDJf/view?usp=sharing',
  },
  {
    slug: 'sleepzy',
    title: 'Designing Sleepzy: A Mobile Interface for Lucid Dream Induction via Smart Pillow Technology',
    authors: 'Sumudu Ratnayake, Dinuka Wickramasinghe, Sasini Lekamalage, Senuda Weliwatta, Dr. Pradeep Kalansooriya',
    venue: '18th International Research Conference, General Sir John Kotelawala Defence University (KDU IRC - 2025)',
    year: '2025',
    date: 'Oct 1, 2025',
    status: 'Published',
    typeNote: 'International conference · Abstract published in proceedings',
    summary: 'A user-centred mobile interface and adaptive intervention framework for REM detection, personalised sensory cues, and sleep support.',
    proceeding: 'https://irc.kdu.ac.lk/2025/documents/2025/abstracts/irc25_abstract_book_foc.pdf',
    presentation: 'https://drive.google.com/file/d/1ycvDn0Qfl462uzNj-8cOlsdZpxoelaQ1/view?usp=sharing',
  },
  {
    slug: 'bridging-sensory-frontiers-assistive-tech',
    title: 'Bridging Sensory Frontiers: A Spatio-Semantic Framework for Context-Aware Assistive Technology for the Deaf and Blind',
    authors: 'Sumudu Ratnayake, Dinuka Wickramasinghe, Mrs. Dharani Abeysinghe, Dr. Kaneeka Vidanage, Prof. Sabyasachi Bhattacharyya',
    venue: 'ICCUBEA-2026 - IEEE International Conference',
    year: '2026',
    status: 'Accepted',
    typeNote: 'IEEE international conference · Full paper accepted · Presentation, proceedings, and IEEE Xplore publication in progress',
    summary: 'A spatio-semantic framework for context-aware assistive technology serving people who are Deaf and people who are blind.',
  },
  {
    slug: 'intelligent-environmental-perception-knowledge-graphs',
    title: 'Intelligent Environmental Perception: Mitigating Cognitive Overload in Assistive Technologies via Knowledge Graphs',
    authors: 'Sumudu Ratnayake, Dinuka Wickramasinghe, Mrs. Dharani Abeysinghe, Dr. Kaneeka Vidanage',
    venue: 'YSCMR-2026',
    year: '2026',
    status: 'Needs review',
    typeNote: 'International conference · Abstract only · Under review',
    summary: 'A knowledge-graph approach to mitigating cognitive overload in assistive technologies through more intelligent environmental perception.',
  },
];

export const writing: WritingPost[] = [
  {
    slug: 'the-joy-of-seeing-something-work',
    title: 'The Joy of Seeing Something I Built Actually Work',
    excerpt: 'From a file saved in Notepad to projects that became something much bigger.',
    category: 'Journey', tags: ['building', 'learning'], featured: true, status: 'Published',
    date: 'Aug 12, 2026', readingTime: '3 min read',
    outline: ['The first satisfying feedback loop', 'Why working prototypes change how I think', 'Keeping that feeling as systems get larger'],
    blocks: [
      { type: 'quote', text: 'Computers… fascinating stuff.' },
      { type: 'paragraph', text: 'I don’t remember one dramatic moment when I decided I wanted to work with computers. What I remember is the feeling of making one do something I had imagined.' },
      { type: 'paragraph', text: 'It started small.' },
      { type: 'paragraph', text: 'In school, we learned HTML, and I went a little crazy with it. W3Schools was practically open in one browser tab at all times. We started with headings and paragraphs, then buttons and forms. At some point, I decided to combine everything I’d learned into something of my own: a little questionnaire called **“Favourites of Yours!”**' },
      { type: 'paragraph', text: 'I thought, I can ask people about their favourite colour, favourite food, and all sorts of other things. Nothing groundbreaking. Just an HTML file I’d written myself.' },
      { type: 'paragraph', text: 'But the strange thing was that it actually worked.' },
      { type: 'paragraph', text: 'I had typed all the code into Notepad, saved it as an HTML file, opened it in a browser, and suddenly there was something on the screen that wasn’t there before.' },
      { type: 'paragraph', text: 'That was the part that got me.' },
      { type: 'paragraph', text: 'It made me start thinking:' },
      { type: 'quote', text: 'What if I did this? Can I make this?' },
      { type: 'paragraph', text: 'I think I’ve been chasing that question ever since.' },
      { type: 'paragraph', text: 'The more I learned, the more I wanted to build. CSS made the little pages feel fancier. Later, Python opened up an entirely different kind of possibility. Instead of making things appear on a page, I could make the computer actually *do* things.' },
      { type: 'paragraph', text: 'I built calculators. Decision-makers. Small programs that solved problems I had thought of just because I wanted to see whether I could make them work.' },
      { type: 'paragraph', text: 'Eventually, I built a terminal-based POS system.' },
      { type: 'paragraph', text: 'It was still a small project, and it definitely wasn’t the sort of software you would trust with a real shop. But by that point, the excitement wasn’t really about the program itself anymore. It was about taking a problem, breaking it apart, and slowly turning the pieces into something that worked.' },
      { type: 'paragraph', text: 'Then something happened that made that feeling even better.' },
      { type: 'paragraph', text: 'A friend reached out for help with a Python assignment. It turned out he was building a POS system too.' },
      { type: 'paragraph', text: 'I was able to help him work through it, and somewhere in the middle of explaining functions and breaking the problem into smaller pieces, I realised I had actually learned more than I thought I had.' },
      { type: 'paragraph', text: 'I showed him things I’d figured out by building my own projects.' },
      { type: 'paragraph', text: 'And that felt different.' },
      { type: 'paragraph', text: 'At first, the joy had been:' },
      { type: 'paragraph', text: '**I made something.**' },
      { type: 'paragraph', text: 'Then it became:' },
      { type: 'paragraph', text: '**I made something useful.**' },
      { type: 'paragraph', text: 'And eventually:' },
      { type: 'paragraph', text: '**Something I learned can help someone else build something too.**' },
      { type: 'paragraph', text: 'University just made that playground I had much bigger.' },
      { type: 'paragraph', text: 'The little experiments became software projects, competitions became excuses to build things I’d never built before, and I kept jumping between completely different areas: education, healthcare, gaming, green tech, agri-tech, and whatever else happened to catch my attention.' },
      { type: 'paragraph', text: 'The scale changed.' },
      { type: 'paragraph', text: 'The feeling didn’t.' },
      { type: 'paragraph', text: 'Every time something I’d written finally worked, every time I rewrote a piece of code and watched it behave better, there was still that same little moment of satisfaction.' },
      { type: 'paragraph', text: 'That moment when something that existed only in my head suddenly existed somewhere else too.' },
      { type: 'paragraph', text: 'I think that’s what I love most about building things.' },
      { type: 'paragraph', text: 'Not necessarily the finished product.' },
      { type: 'paragraph', text: 'It’s that strange moment between *“I wonder if I can make this”* and *“Wait. It actually works.”*' },
      { type: 'paragraph', text: 'There is something incredibly satisfying about making something exist that didn’t exist before.' },
      { type: 'paragraph', text: 'And maybe that’s why, all these years later, I still keep asking the same question:' },
      { type: 'quote', text: 'What if I did this? Can I make this?' },
    ],
  },
  {
    slug: 'learning-programming-before-ai',
    title: 'Learning Programming Before AI',
    excerpt: 'Books, documentation, Stack Overflow, experiments, and the habits that came from learning before assistants became part of the workflow.',
    category: 'Journey', tags: ['learning', 'AI', 'fundamentals'], featured: true, status: 'Planned',
    outline: ['Learning from slow feedback', 'Why I avoided AI for OOP and DSA', 'How I use AI now without outsourcing understanding'],
  },
  {
    slug: 'the-unexpected-reason-i-started-research',
    title: 'The Unexpected Reason I Started Research',
    excerpt: 'What began as a practical goal to present at a conference became a genuine interest in difficult questions, publishing, and explaining ideas.',
    category: 'Research Rabbit Holes', tags: ['research', 'journey'], status: 'Planned',
    outline: ['A conference as the initial goal', 'Learning what research actually asks of you', 'Why I stayed interested'],
  },
  {
    slug: 'building-is-my-favourite-way-to-learn',
    title: 'Building Things Is My Favourite Way to Learn',
    excerpt: 'Why prototypes, mistakes, and working systems are the most useful map I have found for learning unfamiliar ideas.',
    category: 'Build Logs', tags: ['building', 'learning'], status: 'Planned',
    outline: ['Turning ambiguity into questions', 'What implementation reveals', 'A practical loop for learning by building'],
  },
];

export const currently = {
  updated: 'Add date',
  items: [
    { label: 'Building', text: 'Add current product, prototype, or startup work.' },
    { label: 'Researching', text: 'Ontology-driven VR tutoring, agentic AI, XAI, and semantic systems.' },
    { label: 'Writing', text: 'Preparing the first essays for this site.' },
    { label: 'Learning', text: 'Add the topic, tool, or question currently being explored.' },
    { label: 'Reading', text: 'Add the current book, paper, or reading list.' },
    { label: 'Working on', text: 'Add a public-safe summary of current professional or startup work.' },
  ],
};

export const experience = [
  { period: 'Jun 2026 - Present', title: 'Software Engineer Intern', place: 'WSO2', detail: 'Working in the Open Healthcare team within the Solutions Business Unit, one of 7 Engineering R&D business units, focusing on interoperability, MCP, and other healthcare-related products built on WSO2 middleware.' },
  { period: 'Jan 2026 - Present', title: 'Associate', place: 'Claptac', detail: 'A software development studio started with friends from university, building web applications and custom software, modern React/Next.js frontends backed by robust APIs and enterprise-grade Java backends. Still early days.' },
];

export const education = [
  { period: '2023 - Present', title: 'BSc (Hons) in Computer Science', place: 'Undergraduate', detail: 'Mainly focusing on AI, ML, multi-agent systems, and explainable AI.' },
  { period: '2019 - 2021', title: 'GCE Advanced Level', place: 'Physical Science stream', detail: 'Combined Mathematics, Physics, and Information & Communication Technology.' },
  { period: '2018', title: 'GCE Ordinary Level', place: 'Secondary education', detail: '' },
];

export const community = [
  { period: 'Mar 2025 - Feb 2026', title: 'Secretary', place: 'BCS Student Chapter, Kotelawala Defence University', detail: '' },
  { period: 'Mar 2025 - Mar 2026', title: 'Head of Industry Engagement', place: 'IEEE Computer Society of KDU', detail: '' },
  { period: 'Feb 2023 - Feb 2025', title: 'Member, Secretary Team', place: 'IEEE Computer Society of KDU', detail: 'As it is a newly established society in the university, had the privilege to work as an organising committee member of the secretary team for several projects, and also got the chance to work as the Event Secretary for the CSR Project organised by the Computer Society to spread awareness on the IT industry and future directions among school learners.' },
  { period: 'Feb 2024 - Feb 2025', title: 'Member, Secretary Team', place: 'BCS Student Chapter, Kotelawala Defence University', detail: 'Worked under the event leads for events such as Cre8X, an inter-university UI/UX design competition.' },
  { period: 'Apr 2024 - Mar 2025', title: 'Member, Secretary Team', place: 'IEEE Student Branch of KDU', detail: 'Worked under event leads for events such as the IEEE Day, and FRP projects done by the student branch.' },
  { period: 'Feb 2023 - Feb 2024', title: 'Member, Photography Team', place: 'BCS Student Chapter, Kotelawala Defence University', detail: 'Worked under the event leads for events such as ManageX and TechXhibit, a hardware and software exhibition organised by the Student Branch to display and select the best projects done by university undergraduates.' },
];

export const achievements = [
  { year: '2025', title: "Dean's List", result: 'YGPA 3.7553 / 4.0' },
  { year: '2025', title: 'ICDS 2025 Mini-Hackathon', result: 'Top 15 finalist', description: "National-level data science competition organised by the Stat Circle, Faculty of Science, University of Colombo, in collaboration with OCTAVE, John Keells Group." },
  { year: '2025', title: 'Code with WIE', result: '1st Runner-Up', description: 'The 7th annual innovation challenge by IEEE WIE Affinity Group Sri Lanka. Built CareSync, a tool helping healthcare professionals manage burnout through intelligent workload balancing and wellness insights.' },
  { year: '2025', title: 'Data Odyssey', result: 'Best Use of Technology', description: 'Inter-university software innovation competition by the AI & Data Science Club of KDU. Recognised for Athena, an AI journal for cognitive wellness supporting people with dementia.' },
  { year: '2025', title: 'InnovateX University Edition', result: '1st Runner-Up', description: 'National hackathon by Zebra Technologies. Built a real-time AI-powered retail analytics and optimisation platform in a 4-hour final, competing among 17 top university teams.' },
  { year: '2025', title: 'CodeRally 6.0', result: 'Advanced Tier finalist', description: 'National hackathon by the IEEE Computer Society of IIT. Ranked 8th in selection rounds and advanced to the final 24-hour hackathon as Team F4Version2.' },
  { year: '2025', title: 'Tech-Triathlon', result: 'Top 8 finalist from 170+ teams', description: 'Three-phase national competition (hackathon, designathon, datathon) organised by Rootcode, as Team Mental Breakdowns.' },
  { year: '2024', title: "Vice Chancellor's List", result: 'YGPA 3.82 / 4.0' },
  { year: '2024', title: 'Data Odyssey', result: 'Champion, Green AI', description: 'Inter-university software innovation competition by the AI & Data Science Club of KDU. Green AI placed first among 100+ participants.' },
  { year: '2023', title: "Dean's List", result: 'YGPA 3.78 / 4.0' },
];
