import type { CaseStudy, ResearchEntry, WritingPost } from '../types';

export const site = {
  name: 'Sumudu Ratnayake',
  shortName: 'SR',
  headline: 'Curious builder exploring research, AI, and software.',
  subhead: 'Turning ideas into working systems that matter.',
  email: 'ishadi.leoni@gmail.com',
  location: 'Sri Lanka',
  github: 'https://github.com/Lilvamp237',
  linkedin: 'https://www.linkedin.com/in/sumudu-ratnayake-782b90235/',
  cv: 'cv/Sumudu Ishadi Ratnayake.pdf',
  avatar: 'sumudu-profilepic.jpeg',
};

export const navigation = [
  { label: 'Home', path: '/' },
  { label: 'About', path: '/about' },
  { label: 'Projects', path: '/projects' },
  { label: 'Research', path: '/research' },
  { label: 'Writing', path: '/writing' },
  { label: 'Contact', path: '/contact' },
];

export const researchInterests = [
  'Agentic AI',
  'Multi-agent systems',
  'Explainable AI',
  'Human–computer interaction',
  'Accessibility',
  'Educational technology',
  'Virtual & extended reality',
  'Ontologies & semantic systems',
  'Knowledge graphs',
  'Responsible AI',
];

export const projects: CaseStudy[] = [
  {
    slug: 'dengue-allocator',
    title: 'DengueSentinel — dengue vector-control resource allocator',
    label: 'Decision support · Public health',
    summary: 'A forecasting and optimisation platform that predicts dengue transmission risk 2–4 weeks ahead and allocates vector-control teams within budget constraints.',
    implementation: 'A three-stage pipeline forecasts district-level risk with SARIMA/LightGBM/seasonal-naive ensembles, estimates intervention impact with SEI-SIR compartmental modelling, and allocates teams via integer linear programming (PuLP/CBC). Role-based Streamlit dashboards serve the public, hospital staff, regional officers, and administrators, with strict data-provenance tracking and an offline-first design.',
    technologies: ['Python', 'LightGBM', 'statsmodels', 'PuLP / CBC', 'Streamlit'],
    image: 'projects/dengue-allocator.png',
    team: ['Dinuka', 'Hasindu'],
    repository: 'https://github.com/Wicky2002/dengue-allocator',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'nourish-loop',
    title: 'NourishLoop',
    label: 'Decision support · EdTech',
    summary: 'A closed-loop, human-in-the-loop platform for nutritious, affordable, low-waste school meal planning in Sri Lanka.',
    implementation: 'A Next.js/FastAPI system forecasts meal demand with an exponential-moving-average model, optimises meal recommendations against nutrition and budget constraints, and retrains its demand model from real consumption data (attendance, leftovers), with dual dashboards for meal planners and coordinators.',
    technologies: ['Next.js', 'TypeScript', 'FastAPI', 'shadcn/ui', 'Recharts'],
    image: 'projects/nourish-loop.png',
    team: ['Dinuka'],
    repository: 'https://github.com/Lilvamp237/nourish-loop',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'pokemon-meta-balance',
    title: 'Pokémon predictive meta-balance system',
    label: 'Applied ML · Game design tooling',
    summary: 'A machine learning system analysing Pokémon stats and typing to help assess game-balance risk and predict competitive viability across generations.',
    implementation: 'An unsupervised Isolation Forest flags mathematically anomalous stat designs for balance review, while a Random Forest regressor predicts how many future generations a design stays competitively viable, surfaced through an explainable Streamlit dashboard with separate views for designers and competitive players.',
    technologies: ['Python', 'scikit-learn', 'Streamlit', 'Pandas'],
    image: 'projects/pokemon-meta-balance.png',
    team: ['Dinuka', 'Sasini', 'Gimhani', 'Malick', 'Senuda'],
    repository: 'https://github.com/Lilvamp237/Predictive-Meta-Balance-System-for-Pokemon',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'ithihaasa-guru',
    title: 'Ithihaasa Guru',
    label: 'AI · EdTech · Ontologies',
    summary: 'An AI platform that automates scoring and feedback for open-ended Sri Lankan colonial-history questions, delivered in Sinhala medium.',
    implementation: 'A LangGraph workflow combines an OWL ontology (RDFLib) with RAG retrieval over Grade 8–11 textbooks (FAISS) and a locally-run LLM (Ollama, gemma3:12b) to generate evidence-based scoring and detailed Sinhala feedback with confidence scoring, through a Streamlit interface.',
    technologies: ['LangGraph', 'FAISS', 'OWL / RDFLib', 'Ollama', 'Streamlit'],
    image: 'projects/ithihaasa-guru.png',
    repository: 'https://github.com/Lilvamp237/Ithihaasa-Guru',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'autonomous-swarms',
    title: 'Autonomous vehicle swarms — social value orientation study',
    label: 'Simulation · Agentic systems',
    summary: 'A simulation of autonomous vehicle swarms at urban intersections, studying how individual social preferences shape collective traffic outcomes.',
    implementation: 'Agents built on Eclipse SUMO and the TraCI client use Social Value Orientation utility functions and Nash-style conflict resolution to decide yield/proceed behaviour at intersections. An inverse-reinforcement-learning module estimates each agent’s SVO angle from observed driving, while Neo4j records interaction history alongside CSV telemetry (delay, throughput, collisions).',
    technologies: ['Python', 'Eclipse SUMO', 'TraCI', 'Neo4j'],
    image: 'projects/autonomous-swarms.png',
    team: ['Dinuka', 'Sasini', 'Senuda'],
    repository: 'https://github.com/Lilvamp237/Autonomous-swarms',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'athena',
    title: 'Athena',
    label: 'Competition project · AI · Cognitive wellness',
    summary: 'An AI-powered platform supporting cognitive wellness and dementia care management for patients and caregivers.',
    problem: 'Care teams need a clearer way to track daily activity, medication, wellness signals, and collaboration around people living with dementia.',
    context: 'Built as a competition project and recognised for its use of technology at Data Odyssey 2025.',
    implementation: 'The existing portfolio describes a React interface with analytics, sentiment tracking, medication management, team collaboration, and Python/Node.js AI features.',
    technologies: ['React', 'Python', 'Node.js', 'Chart.js', 'Jest'],
    outcome: 'Best Use of Technology — Data Odyssey 2025.',
    image: 'projects/athena-1.png',
    team: ['Dinuka'],
    status: 'Completed',
    featured: true,
    needs: ['Repository URL'],
  },
  {
    slug: 'caresync',
    title: 'CareSync',
    label: 'Competition project · Full-stack software',
    summary: 'A team coordination and burnout-management platform with scheduling, wellness tracking, and secure collaboration for medical professionals.',
    problem: 'Demanding shifts, fragmented team communication, and limited visibility into personal wellness can compound burnout for medical professionals.',
    context: 'Developed for Code with WIE 2025.',
    implementation: 'A responsive Next.js application with a unified calendar, shift swaps, priority announcements, habit logs, Supabase, PostgreSQL, and row-level security.',
    technologies: ['Next.js', 'TypeScript', 'Supabase', 'PostgreSQL', 'Recharts'],
    outcome: '1st Runner-Up — Code with WIE 2025.',
    image: 'projects/caresync.png',
    team: ['Dinuka'],
    repository: 'https://github.com/Lilvamp237/cww',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'bookstore-ontology-agents',
    title: 'Intelligent bookstore with ontology & multi-agent simulation',
    label: 'AI systems · Knowledge representation',
    summary: 'An autonomous bookstore simulation combining OWL, SWRL reasoning, agent-based modelling, and a graph database.',
    problem: 'Explore how domain knowledge and autonomous agents can coordinate inventory and customer activity in a transparent simulated environment.',
    implementation: 'OWL models domain knowledge; SWRL and Pellet infer conditions such as low stock; Mesa agents act on those inferences; Neo4j records relationships and transactions; Streamlit exposes live controls and visualisation.',
    technologies: ['Python', 'OWL / SWRL', 'Mesa', 'Neo4j', 'Streamlit'],
    image: 'projects/bookstore-ontology.png',
    repository: 'https://github.com/Lilvamp237/Bookstore-Management-System-with-Ontology-and-Multi-Agent-Simulation',
    status: 'Completed',
    featured: true,
  },
  {
    slug: 'hotel-agentic-optimizer',
    title: 'Agentic guest experience optimiser',
    label: 'Hackathon · Agentic AI',
    summary: 'A multi-stage system combining customer segmentation, prediction, RAG, weather, and local context for personalised hotel communications.',
    context: 'Developed for the Mini Hackathon semi-finals organised by the Statistics Circle, University of Colombo.',
    implementation: 'K-Means discovers behavioural segments, a Random Forest predicts segments, and an agentic RAG workflow produces context-aware messages in a Streamlit dashboard.',
    technologies: ['Python', 'scikit-learn', 'RAG', 'Streamlit', 'Pandas'],
    image: 'projects/hotel-experience.png',
    team: ['Dinuka', 'Savini'],
    repository: 'https://github.com/Lilvamp237/Agentic-Based-Hotel-Booking-Guest-Experience-Optimizer',
    status: 'Completed',
  },
  {
    slug: 'green-ai',
    title: 'Green AI',
    label: 'Sustainability · Data visualisation',
    summary: 'A web platform visualising AI model emissions and cloud data-centre energy use to support lower-carbon decisions.',
    implementation: 'A Vue 3 interface presents maps and dashboards, while Django processes datasets and supports carbon-footprint estimates and recommendations.',
    technologies: ['Vue 3', 'Django', 'Python', 'Pandas', 'REST APIs'],
    outcome: 'Champion — Data Odyssey 2024, as recorded in the existing portfolio.',
    image: 'projects/green-ai.jpg',
    team: ['Sasini', 'Amna', 'Yuthara'],
    repository: 'https://github.com/Lilvamp237/green-ai-new',
    status: 'Completed',
  },
  {
    slug: 'egov-platform',
    title: 'eGOV',
    label: 'Competition project · Civic systems',
    summary: 'A multi-portal e-government platform for citizen services, administration, and analytics.',
    implementation: 'A Next.js monorepo coordinates citizen, admin, and analytics applications with shared packages, Supabase/PostgreSQL, role-based access, and Docker development workflows.',
    technologies: ['Next.js', 'TypeScript', 'Supabase', 'PostgreSQL', 'Docker'],
    image: 'projects/egov-monorepo.jpg',
    team: ['Team ClapTac'],
    repository: 'https://github.com/HasinduNimesh/Mental-Breakdown_eGOV',
    status: 'Completed',
  },
  {
    slug: 'smart-home-energy',
    title: 'Smart home energy tracker',
    label: 'Full-stack · ML · Semantic web',
    summary: 'A system that tracks household energy, predicts near-term consumption, and uses semantic rules to suggest lower-cost usage patterns.',
    implementation: 'React and Flask provide the product layer; engineered time-series features feed a regression model; an RDF ontology and SPARQL rules reason over time-of-use pricing.',
    technologies: ['React', 'Flask', 'scikit-learn', 'RDF / SPARQL', 'SQLite'],
    team: ['Dinuka'],
    repository: 'https://github.com/Lilvamp237/Smart-Home-Energy-Tracker',
    status: 'Completed',
    needs: ['Project image'],
  },
  {
    slug: 'audio-denoising',
    title: 'Sup_Audio',
    label: 'Deep learning · Desktop software',
    summary: 'An end-to-end audio denoising application using a U-Net model and a desktop interface for recording, playback, and cleaned output.',
    implementation: 'The pipeline transforms audio with STFT, performs spectrogram inference in fixed-length chunks, reconstructs output, and exposes the workflow through PyQt5.',
    technologies: ['Python', 'TensorFlow', 'Keras', 'PyQt5', 'librosa'],
    image: 'projects/audio-denoising.png',
    repository: 'https://github.com/Lilvamp237/Audio-Denoising-System-using-Deep-Learning-and-PyQt-UI-',
    status: 'Completed',
  },
  {
    slug: 'face-recognition-attendance',
    title: 'Face recognition attendance system',
    label: 'Computer vision · Desktop software',
    summary: 'A real-time attendance system with registration, identity verification, local records, and weekly statistics.',
    implementation: 'OpenCV and DeepFace provide face processing and embedding-based matching; PyQt5 supports registration, attendance, and reporting workflows.',
    technologies: ['Python', 'OpenCV', 'DeepFace', 'PyQt5'],
    image: 'projects/face-recognition.png',
    repository: 'https://github.com/Lilvamp237/face_recognition_attendance_system',
    status: 'Completed',
  },
  {
    slug: 'budget-buddy',
    title: 'Budget Buddy',
    label: 'University project · Java',
    summary: 'A desktop personal-finance manager for income, expenses, balances, and budget summaries.',
    context: 'Built as a second-year object-oriented programming group assignment.',
    implementation: 'A Java Swing interface organised with an MVC-inspired structure, reusable GUI components, event-driven behaviour, and local file handling.',
    technologies: ['Java', 'Swing', 'File I/O', 'MVC'],
    image: 'projects/budget-buddy.jpg',
    team: ['Sasini', 'Senuda'],
    repository: 'https://github.com/Lilvamp237/Budget-Buddy---Financial-Tracker',
    status: 'Completed',
  },
  {
    slug: 'drug-category-prediction',
    title: 'Mental health-driven drug category prediction',
    label: 'Data science · Healthcare',
    summary: 'A machine learning system predicting drug categories from mental health conditions and usage patterns using XGBoost with PSO-based feature selection.',
    context: 'Built for the preliminary round of the ICDS 2025 Mini-Hackathon, organised by the University of Colombo with OCTAVE (JKH Group).',
    implementation: 'A preprocessing pipeline with scaling, imputation, and Particle Swarm Optimization for feature selection feeds an XGBoost classifier, with automated encoding/decoding and reproducible submission generation.',
    technologies: ['Python', 'XGBoost', 'scikit-learn', 'pandas', 'NumPy'],
    repository: 'https://github.com/Lilvamp237/Mental-health-condition-related-to-drug-usage---Drug-Prediction',
    image: 'projects/drug-prediction.jpg',
    team: ['Dinuka'],
    status: 'Completed',
  },
  {
    slug: 'smart-study-companion',
    title: 'Smart Study Companion',
    label: 'Full-stack · AI/NLP',
    summary: 'A full-stack web app helping students track study sessions, take notes, and use AI tools for summarisation, flashcards, quizzes, and study plans.',
    implementation: 'A Django REST Framework backend and React frontend integrate Hugging Face models (BART, DistilBERT) for summarisation, flashcard creation, question answering, sentiment analysis, keyword extraction, and quiz generation, with JWT auth and progress analytics.',
    technologies: ['Django', 'React', 'Hugging Face Transformers', 'PyTorch', 'JWT'],
    repository: 'https://github.com/Wicky2002/smart-study-companion',
    image: 'projects/study-companion.jpg',
    team: ['Dinuka'],
    status: 'Completed',
  },
  {
    slug: 'moot-society-website',
    title: 'Moot Society of Sri Lanka Law College — official website',
    label: 'Full-stack · CMS',
    summary: 'A responsive website for the Moot Society showcasing events, achievements, news, and a gallery, built on a Next.js and Strapi CMS stack.',
    implementation: 'A Next.js frontend with scroll animations and a lightbox gallery consumes a Strapi CMS backend with PostgreSQL/SQLite, Cloudinary media uploads, and role-based authentication. The site is SEO-optimised and production-ready.',
    technologies: ['Next.js', 'TypeScript', 'Strapi CMS', 'Tailwind CSS', 'Cloudinary'],
    repository: 'https://github.com/Lilvamp237/moot-society-website',
    image: 'projects/moot-society.png',
    team: ['Dinuka'],
    status: 'Completed',
  },
  {
    slug: 'sumudus-todo-list',
    title: "Sumudu's ToDo List — smart Android task manager",
    label: 'Mobile · Android',
    summary: 'An Android task manager with offline support, Firebase sync, and exact alarm-based reminders that persist across reboots.',
    implementation: 'Built with Jetpack Compose and Kotlin on an MVVM architecture. Room handles local persistence for offline use, Firebase Authentication and Firestore provide sync, and AlarmManager with BroadcastReceivers drives exact, reboot-safe reminders. Material Design 3 supports adaptive light/dark theming.',
    technologies: ['Kotlin', 'Jetpack Compose', 'Room', 'Firebase', 'Hilt'],
    repository: 'https://github.com/Lilvamp237/SumudusToDoList',
    image: 'projects/todo-android.jpg',
    status: 'Completed',
  },
  {
    slug: 'localloop',
    title: 'Localloop — full-stack service integration platform',
    label: 'Hackathon · Full-stack',
    summary: 'A full-stack app demonstrating REST-based communication between a Ballerina backend and a Vite-powered frontend.',
    context: 'Developed for the Innovate with Ballerina 2025 competition.',
    implementation: 'A Ballerina backend exposes RESTful APIs for data processing and service logic; a Vite frontend consumes them for a fast, responsive UI, emphasising clean separation between layers and real-time data flow.',
    technologies: ['Ballerina', 'Vite', 'JavaScript', 'REST APIs'],
    image: 'projects/localloop.jpg',
    team: ['Dinuka', 'Sasini', 'Senuda'],
    status: 'Completed',
    needs: ['Repository URL'],
  },
];

export const publications: ResearchEntry[] = [
  {
    slug: 'inclusive-digital-infrastructure',
    title: 'AI-Driven Inclusive Digital Infrastructure: A Unified Cognitive Load Framework for Accessible Smart Education in Sustainable Cities',
    authors: 'Dinuka Wickramasinghe, Sumudu Ratnayake, Kaneeka Vidanage, Dharani Abeysinghe, Sabyasachi Bhattacharyya',
    venue: 'ICSDS India-2025 — International Conference on Sustainable Developments in Computer Engineering, Green Technology & Smart Systems',
    year: '2025',
    status: 'Published',
    typeNote: 'International conference · Full paper in proceedings · Book chapter (CRC Press, Taylor & Francis)',
    summary: 'An accessibility framework for smart education that adapts multimodal content for Deaf and Hard of Hearing and Blind and Visually Impaired users using cognitive-load estimation.',
    paper: 'https://www.taylorfrancis.com/chapters/edit/10.1201/9781003743774-148/ai-driven-inclusive-digital-infrastructure-unified-cognitive-load-framework-accessible-smart-education-sustainable-cities-dinuka-wickramasinghe-sumudu-ratnayake-kaneeka-vidanage-dharani-abeysinghe-sabyasachi-bhattacharyya',
    needs: ['Citation'],
  },
  {
    slug: 'bridging-semantic-gap-deaf-education',
    title: 'Bridging the Semantic Gap in Deaf Education: A Review of Virtual Reality Platforms and Knowledge-Based AI Approaches',
    venue: 'JCoS-2026',
    year: '2026',
    status: 'Published',
    typeNote: 'Local conference · Abstract only · Published in proceedings',
    summary: 'A review of virtual reality platforms and knowledge-based AI approaches for bridging the semantic gap in Deaf education.',
    needs: ['Authors', 'Paper/proceedings link', 'Presentation', 'Citation'],
  },
  {
    slug: 'sleepzy',
    title: 'Designing Sleepzy: A Mobile Interface for Lucid Dream Induction via Smart Pillow Technology',
    venue: '18th International Research Conference — General Sir John Kotelawala Defence University',
    year: '2025',
    date: 'Oct 1, 2025',
    status: 'Published',
    typeNote: 'International conference · Abstract published in proceedings',
    summary: 'A user-centred mobile interface and adaptive intervention framework for REM detection, personalised sensory cues, and sleep support.',
    proceeding: 'https://irc.kdu.ac.lk/2025/documents/2025/abstracts/irc25_abstract_book_foc.pdf',
    needs: ['Authors', 'Presentation', 'Citation'],
  },
  {
    slug: 'green-cloud-framework',
    title: 'A Unified Framework for SLA-Aware and Carbon-Conscious Green Cloud Computing: A Holistic Approach to Sustainable Infrastructure',
    venue: '18th International Research Conference — General Sir John Kotelawala Defence University',
    year: '2025',
    date: 'Oct 1, 2025',
    status: 'Published',
    typeNote: 'International conference · Abstract published in proceedings',
    summary: 'A multi-objective framework balancing energy, carbon emissions, and service-level agreements in green cloud computing.',
    proceeding: 'https://irc.kdu.ac.lk/2025/documents/2025/abstracts/irc25_abstract_book_foc.pdf',
    needs: ['Authors', 'Presentation', 'Citation'],
  },
  {
    slug: 'sustainability-awareness-apps',
    title: 'Enhancing Sustainability Awareness Through Mobile Applications: A Comparative Case Study and Analysis',
    venue: '18th International Research Conference — General Sir John Kotelawala Defence University',
    year: '2025',
    date: 'Oct 1, 2025',
    status: 'Published',
    typeNote: 'International conference · Abstract published in proceedings',
    summary: 'A comparative analysis of sustainability applications identifying technical and interface gaps that affect retention and real-world impact.',
    proceeding: 'https://irc.kdu.ac.lk/2025/documents/2025/abstracts/irc25_abstract_book_fmsh.pdf',
    needs: ['Authors', 'Presentation', 'Citation'],
  },
  {
    slug: 'bridging-sensory-frontiers-assistive-tech',
    title: 'Bridging Sensory Frontiers: A Spatio-Semantic Framework for Context-Aware Assistive Technology for the Deaf and Blind',
    venue: 'ICCUBEA-2026 — IEEE International Conference',
    year: '2026',
    status: 'Accepted',
    typeNote: 'IEEE international conference · Full paper accepted · Presentation, proceedings, and IEEE Xplore publication in progress',
    summary: 'A spatio-semantic framework for context-aware assistive technology serving people who are Deaf and people who are blind.',
    needs: ['Authors', 'Paper link', 'Presentation', 'Citation'],
  },
  {
    slug: 'intelligent-environmental-perception-knowledge-graphs',
    title: 'Intelligent Environmental Perception: Mitigating Cognitive Overload in Assistive Technologies via Knowledge Graphs',
    venue: 'YSCMR-2026',
    year: '2026',
    status: 'Needs review',
    typeNote: 'International conference · Abstract only · Under review',
    summary: 'A knowledge-graph approach to mitigating cognitive overload in assistive technologies through more intelligent environmental perception.',
    needs: ['Authors', 'Outcome', 'Paper link'],
  },
  {
    slug: 'ontology-diagnostic-agents-sign-language',
    title: 'Ontology-Grounded Diagnostic Agents for Explainable Near-Miss Feedback in Sign-Language Tutoring',
    venue: 'SLAAI-ICAI-2026 — IEEE International Conference',
    year: '2026',
    status: 'Needs review',
    typeNote: 'IEEE international conference · IEEE Xplore · Under review',
    summary: 'Ontology-grounded diagnostic agents that generate explainable near-miss feedback for sign-language tutoring systems.',
    needs: ['Authors', 'Outcome', 'Paper link'],
  },
  {
    slug: 'dynamic-svo-autonomous-vehicle-swarms',
    title: 'Dynamic Social Value Orientation in Autonomous Vehicle Swarms: A Framework for Collective Urban Intelligence',
    venue: 'ICTer-2026',
    year: '2026',
    status: 'Needs review',
    typeNote: 'International conference · Full paper · Under review',
    summary: 'A framework for collective urban intelligence based on dynamic social value orientation across autonomous vehicle swarms.',
    project: 'autonomous-swarms',
    needs: ['Authors', 'Outcome', 'Paper link'],
  },
];

export const writing: WritingPost[] = [
  {
    slug: 'the-joy-of-seeing-something-work',
    title: 'The Joy of Seeing Something I Built Actually Work',
    excerpt: 'A reflection on the small, unmistakable moment when an idea stops being abstract and starts behaving like a real thing.',
    category: 'Reflections', tags: ['building', 'learning'], featured: true, status: 'Planned',
    outline: ['The first satisfying feedback loop', 'Why working prototypes change how I think', 'Keeping that feeling as systems get larger'],
  },
  {
    slug: 'learning-programming-before-ai',
    title: 'Learning Programming Before AI',
    excerpt: 'Books, documentation, Stack Overflow, experiments, and the habits that came from learning before assistants became part of the workflow.',
    category: 'Journey', tags: ['learning', 'AI', 'fundamentals'], featured: true, status: 'Planned',
    outline: ['Learning from slow feedback', 'Why I avoided AI for OOP and DSA', 'How I use AI now without outsourcing understanding'],
  },
  {
    slug: 'the-unexpected-reason-i-started-research',
    title: 'The Unexpected Reason I Started Research',
    excerpt: 'What began as a practical goal to present at a conference became a genuine interest in difficult questions, publishing, and explaining ideas.',
    category: 'Research Rabbit Holes', tags: ['research', 'journey'], status: 'Planned',
    outline: ['A conference as the initial goal', 'Learning what research actually asks of you', 'Why I stayed interested'],
  },
  {
    slug: 'building-is-my-favourite-way-to-learn',
    title: 'Building Things Is My Favourite Way to Learn',
    excerpt: 'Why prototypes, mistakes, and working systems are the most useful map I have found for learning unfamiliar ideas.',
    category: 'Build Logs', tags: ['building', 'learning'], status: 'Planned',
    outline: ['Turning ambiguity into questions', 'What implementation reveals', 'A practical loop for learning by building'],
  },
];

export const currently = {
  updated: 'Add date',
  items: [
    { label: 'Building', text: 'Add current product, prototype, or startup work.' },
    { label: 'Researching', text: 'Ontology-driven VR tutoring, agentic AI, XAI, and semantic systems.' },
    { label: 'Writing', text: 'Preparing the first essays for this site.' },
    { label: 'Learning', text: 'Add the topic, tool, or question currently being explored.' },
    { label: 'Reading', text: 'Add the current book, paper, or reading list.' },
    { label: 'Working on', text: 'Add a public-safe summary of current professional or startup work.' },
  ],
};

export const experience = [
  { period: 'Jun 2026 — Present', title: 'Software Engineer Intern', place: 'WSO2', detail: 'Working in the Open Healthcare team within the Solutions Business Unit — one of 7 Engineering R&D business units — focusing on interoperability, MCP, and other healthcare-related products built on WSO2 middleware.' },
  { period: 'Jan 2026 — Present', title: 'Associate', place: 'Claptac', detail: 'A software development studio started with friends from university, building web applications and custom software — modern React/Next.js frontends backed by robust APIs and enterprise-grade Java backends. Still early days.' },
];

export const education = [
  { period: '2023 — Present', title: 'BSc (Hons) in Computer Science', place: 'Undergraduate', detail: 'Mainly focusing on AI, ML, multi-agent systems, and explainable AI.' },
  { period: '2019 — 2021', title: 'GCE Advanced Level', place: 'Physical Science stream', detail: 'Combined Mathematics, Physics, and Information & Communication Technology.' },
  { period: '2018', title: 'GCE Ordinary Level', place: 'Secondary education', detail: '' },
];

export const community = [
  { period: 'Mar 2025 — Feb 2026', title: 'Secretary', place: 'BCS Student Chapter — Kotelawala Defence University', detail: '' },
  { period: 'Mar 2025 — Mar 2026', title: 'Head of Industry Engagement', place: 'IEEE Computer Society of KDU', detail: '' },
  { period: 'Feb 2023 — Feb 2025', title: 'Member — Secretary Team', place: 'IEEE Computer Society of KDU', detail: 'As it is a newly established society in the university, had the privilege to work as an organising committee member of the secretary team for several projects, and also got the chance to work as the Event Secretary for the CSR Project organised by the Computer Society to spread awareness on the IT industry and future directions among school learners.' },
  { period: 'Feb 2024 — Feb 2025', title: 'Member — Secretary Team', place: 'BCS Student Chapter — Kotelawala Defence University', detail: 'Worked under the event leads for events such as Cre8X, an inter-university UI/UX design competition.' },
  { period: 'Apr 2024 — Mar 2025', title: 'Member — Secretary Team', place: 'IEEE Student Branch of KDU', detail: 'Worked under event leads for events such as the IEEE Day, and FRP projects done by the student branch.' },
  { period: 'Feb 2023 — Feb 2024', title: 'Member — Photography Team', place: 'BCS Student Chapter — Kotelawala Defence University', detail: 'Worked under the event leads for events such as ManageX and TechXhibit, a hardware and software exhibition organised by the Student Branch to display and select the best projects done by university undergraduates.' },
];

export const achievements = [
  { year: '2025', title: "Dean's List", result: 'YGPA 3.7553 / 4.0' },
  { year: '2025', title: 'ICDS 2025 Mini-Hackathon', result: 'Top 15 finalist', description: "National-level data science competition organised by the Stat Circle, Faculty of Science, University of Colombo, in collaboration with OCTAVE — John Keells Group." },
  { year: '2025', title: 'Code with WIE', result: '1st Runner-Up', description: 'The 7th annual innovation challenge by IEEE WIE Affinity Group Sri Lanka. Built CareSync, a tool helping healthcare professionals manage burnout through intelligent workload balancing and wellness insights.' },
  { year: '2025', title: 'Data Odyssey', result: 'Best Use of Technology', description: 'Inter-university software innovation competition by the AI & Data Science Club of KDU. Recognised for Athena, an AI journal for cognitive wellness supporting people with dementia.' },
  { year: '2025', title: 'InnovateX University Edition', result: '1st Runner-Up', description: 'National hackathon by Zebra Technologies. Built a real-time AI-powered retail analytics and optimisation platform in a 4-hour final, competing among 17 top university teams.' },
  { year: '2025', title: 'CodeRally 6.0', result: 'Advanced Tier finalist', description: 'National hackathon by the IEEE Computer Society of IIT. Ranked 8th in selection rounds and advanced to the final 24-hour hackathon as Team F4Version2.' },
  { year: '2025', title: 'Tech-Triathlon', result: 'Top 8 finalist from 170+ teams', description: 'Three-phase national competition (hackathon, designathon, datathon) organised by Rootcode, as Team Mental Breakdowns.' },
  { year: '2024', title: "Vice Chancellor's List", result: 'YGPA 3.82 / 4.0' },
  { year: '2024', title: 'Data Odyssey', result: 'Champion — Green AI', description: 'Inter-university software innovation competition by the AI & Data Science Club of KDU. Green AI placed first among 100+ participants.' },
  { year: '2023', title: "Dean's List", result: 'YGPA 3.78 / 4.0' },
];
